name: app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # state management 
  flutter_riverpod: 3.0.3
  riverpod_annotation: 3.0.3
  
  # navigation and routing 
  go_router: 17.0.0

  # used for obscuring api keys
  envied: 1.3.2

  # Firebase
  cloud_firestore: 6.1.0
  firebase_storage: 13.0.4
  firebase_auth: 6.1.2
  firebase_core: 4.2.1
  algolia_helper_flutter: 1.5.0
  cloud_functions: 6.0.4
  firebase_app_check: 0.4.1
  firebase_crashlytics: 5.0.5
  firebase_analytics: 12.0.4


  # others
  intl: 0.20.2
  google_fonts: 6.3.2
  flutter_svg: 2.2.3
  skeletonizer: 2.1.0+1
  carousel_slider: 5.1.1
  flutter_staggered_grid_view: 0.7.0
  font_awesome_flutter: 10.12.0
  photo_view: 0.15.0
  url_launcher: 6.3.2
  flutter_rating_bar: 4.0.1
  timeago: 3.7.1
  pin_code_fields: 8.0.1
  uuid: 4.5.2
  image_picker: 1.2.1
  shared_preferences: 2.5.3
  flutter_native_splash: 2.4.7
  flutter_launcher_icons: 0.14.4

  flutter_image_compress: 2.4.0
  path_provider: 2.1.5
  path: 1.9.1

  # For passing Google Maps API Key to Web
  web: 1.1.1

  # Dependencies for Testing and Fake Repositories
  rxdart: 0.28.0
  mocktail: 1.0.4


  # For Location
  geolocator: 14.0.2
  geocoding: 4.0.0
  google_maps_flutter: 2.14.0
  google_maps_flutter_web: 0.5.14+3

  cached_network_image: 3.4.1
  json_annotation: 4.9.0
  freezed_annotation: 3.1.0
  vector_graphics: 1.1.19
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter    

  flutter_lints: 6.0.0
  build_runner: 2.10.4
  riverpod_generator: 3.0.3
  envied_generator: 1.3.2
  json_serializable: 6.11.2
  freezed: 3.2.3
  vector_graphics_compiler: 1.1.19

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    # Used for Golden Image tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    - assets/images/
    - assets/logo/
    # - assets/fake_data/
    # - assets/fake_data/residence/
    # - assets/fake_data/food/
    # - assets/fake_data/carousel_ads/